#!/bin/sh

php tools/phpunit/vendor/bin/phpunit --no-progress \
tests \
--configuration tools/phpunit/phpunit.xml \
--testdox \
--log-junit $PWD/junit.xml \
--coverage-text \
--coverage-cobertura $PWD/coverage.cobertura.xml \
--exclude-group ignore \
--coverage-filter src
