#!/bin/sh

echo "Running tests for group '${1}'"

rm -rf tmp
mkdir -p tmp
php tools/phpunit/vendor/bin/phpunit --no-progress \
test \
--configuration tools/phpunit/phpunit.xml \
--testdox \
--log-junit $PWD/junit.xml \
--coverage-text \
--coverage-cobertura $PWD/coverage.cobertura.xml \
--group $1 \
--exclude-group ignore \
--coverage-filter src
