name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress
        composer --working-dir tools/phpunit install
        composer --working-dir tools/phpcs install
        composer --working-dir tools/phpstan install

    - name: Run PHPUnit tests
      run: |
        mkdir -p tmp \
        && php tools/phpunit/vendor/bin/phpunit --no-progress \
            test \
            --configuration tools/phpunit/phpunit.xml \
            --testdox \
            --log-junit $PWD/build/junit.xml \
            --coverage-text \
            --coverage-cobertura $PWD/build/coverage.cobertura.xml \
            --coverage-clover $PWD/build/clover.xml \
            --exclude-group ignore \
            --coverage-filter src

    # See https://github.com/php-coveralls/php-coveralls
    - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN_SECRET }}
      run: |
        tools/phpunit/vendor/bin/php-coveralls -v \
        --coverage_clover=$PWD/build/clover.xml \
        --json_path=tools/coveralls-upload.json

    - name: Lint job for PHP code
      run: |
        php tools/phpstan/vendor/bin/phpstan analyse \
        -c tools/phpstan/phpstan.neon \
        --no-interaction \
        --error-format=github

    - name: Lint job for PHP style
      run: tools/phpcs/vendor/bin/phpcs --standard=tools/phpcs/phpcs.xml --report=full src
